services:
  todo-backend:
    build: ./server
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  todo-frontend:
    build:
      context: ./client
      args:
        - VITE_API_URL=/api
    container_name: todo-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_PROXY_TARGET=http://172.23.0.2:5000
    env_file:
      - ./client/.env
    depends_on:
      - todo-backend
