services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
  todo-backend:
    image: todo-backend:jenkins
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - mern-network

  todo-frontend:
    image: todo-frontend:jenkins
    container_name: todo-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_PROXY_TARGET=http://todo-backend:5000
    env_file:
      - ./client/.env
    depends_on:
      - todo-backend
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
